version: "3.8"
name: rentakloud-runtime

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data

  # Web UI for database
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    environment:
      - ADMINER_DESIGN=cyberpunk

  # opensource alternative for redis
  valkey:
    image: bitnami/valkey
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      VALKEY_PASSWORD: ${VALKEY_PASSWORD}
    volumes:
      - valkey-data:/bitnami/valkey/data

  # Monitoring Uptime & Public Status Pages
  uptime-kuma:
    image: louislam/uptime-kuma
    restart: always
    ports:
      - 9100:3001
    volumes:
      - uptime-kuma:/app/data
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  pg-data:
  uptime-kuma:
  valkey-data:
