name: rentakloud-runtime

services:
  # Reverse Proxy
  caddy:
    image: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /www/web:/srv/web # Serving static files
      - /www/admin:/srv/admin
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: